language: node_js
node_js:
 - "8.11.3"

env:
global: 
  - export NODE_ENV=test 
 
notifications:
  email: 
    false
services:
  - postgresql
  
before_script:
  - psql -c 'create database travis_ci_food;' -U postgres
  - npm i -g npm@6.3.0
    
after_script:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info
    
after_success:
- npm run coveralls
